#!/bin/bash
trap "echo -ne '\nstopping container...' && docker stop cognition-pdf2md > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

docker stop cognition-pdf2md

docker build -t cognition-pdf2md-dev -f dev.Dockerfile .

docker run --rm -d \
--name cognition-pdf2md \
-p 7097:3000 \
--mount type=bind,source="$(pwd)"/,target=/app \
--network dev-setup_default \
cognition-pdf2md-dev

docker logs -f cognition-pdf2md